### ISSUE TITLE
Question MarkArrayDirty()

### ISSUE THREAD

**Issue by FlashCoder2024** [MrJohnson2-0/Silicon#2]
how did you made markArrayDirty work with Dumper-7?

**Comment by NotTacs** [comment]
you have to implement it your self you can copy it from the sdk I used, that struct is universal

**Comment by FlashCoder2024** [comment]
> you have to implement it your self you can copy it from the sdk I used, that struct is universal

Okay Thank you so much

**Comment by Vincent1232** [comment]
> you have to implement it your self you can copy it from the sdk I used, that struct is universal

![image](https://github.com/user-attachments/assets/f6b77511-2048-4cb4-ba96-799d6e1610cb)
How do you even remove errors from incoming messages?

**Comment by FlashCoder2024** [comment]
> you have to implement it your self you can copy it from the sdk I used, that struct is universal

How do you even remove errors from incoming messages? ![image](https://github.com/user-attachments/assets/16a7bf28-e3fa-4b70-bde9-7bce804bbbe6)
